### ISSUE TITLE
Use temporary files

### ISSUE THREAD

**Issue by larstvei** [mmagnus/emacs-grammarly#1]
Hi, and thanks for uploading this!

I love the idea of this package, but it should be generalized a bit more. Having `"/home/magnus/Desktop/Grammarly.txt"` in the code does not seem ideal and should be set to more suitable default (maybe something like `user-emacs-directory` or `default-directory`). Also, the README should state that the user can customize by using `setq` rather than asking users to change the source code of your package (that would for instance cause updates to the package to break the user's customization).

As an alternative, I would suggest using a temporary file for each buffer as a default instead of overwriting the same file every time. This can be achieved without making assumptions about the user's system. I favor this approach, and let the user optionally specify a specific file that should be used for all buffers (i.e. let users opt-in to the current solution).

I'll send a pull request if you're open to the idea!

**Comment by mmagnus** [comment]
Dear @larstvei :-) Of course, I love the idea. This is my first plugin (actually like my first anything in Lisp). If you know how to do it please improve it. I can do it if I know more Lisp, for now, this is how it is ;-) I'm open for PRs! :-) Thanks for your feedback. I speak Python, and just a little bit of Lisp.

**Comment by larstvei** [comment]
Good! I've started working on it.

There is one issue that I hadn't expected: even when opening the same file twice, Grammarly decides to make a new document. I have tried to just write the file and reload, but the file is copied either way. This seems like a pretty fundamental issue, so I don't think that reusing the file associated with a buffer is doable (before Grammarly gets a decent API). Since this is (seemingly) the case, I suggest to just make a temporary file for every time `grammarly-save-region-and-run` is called.

Do you agree?

**Comment by larstvei** [comment]
Ok, after looking a bit closer at it I've been able to auto-refresh (calling Applescript from Emacs) when _updating_ a file. Sadly, this does not work when switching to a different file/buffer because using `"open -a"` doesn't seem to do anything when Grammarly is open already.

So maybe it's best to always use the same temporary file and reload it every time. A problem is that it assumes that Grammarly is not already open when it's initially called, and if someone visits another document then it won't switch to the correct document... The only solution I see (now) is to kill Grammarly before sending to it, which seems too crude.

**Comment by mmagnus** [comment]
Thanks a lot @larstvei !

**Comment by larstvei** [comment]
You're most welcome! I've been bummed out that Grammarly doesn't have an API for which I could write an Emacs package. This is a sweet feature to have around in the (hopefully finite) meantime.
I had not thought of calling the OS X app instead, which was a good (and quite hacky) idea!

If it matures a bit, I think it could make a nice package for [melpa](http://melpa.org/). Let me know if you have ideas for how to improve it; I'd be glad to help out!
