### ISSUE TITLE
doesn't seem to work anymore

### ISSUE THREAD

**Issue by incandescentman** [mmagnus/emacs-grammarly#4]
It launches Grammarly but doesn't successfully create a new document within Grammarly.

**Comment by kevzettler** [comment]
Experiencing the same here. Was working fine for a while and just stopped. Not sure what happened.

**Comment by mmagnus** [comment]
Hmm... it seems to work for me Version 1.5.33 (1.5.33). @larstvei, does it work for you?

**Comment by larstvei** [comment]
I tested, and it worked. Then I updated Grammarly and things fell apart...
