### ISSUE TITLE
Would be great to integrate with the website / chrome extension for non mac users 

### ISSUE THREAD

**Issue by tzach** [mmagnus/emacs-grammarly#7]

**Comment by pmatos** [comment]
+1

**Comment by mmagnus** [comment]
Hmm.. but there is not already some Grammarly plugin for websites? 
https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen
or I missed the point of the question?
