### ISSUE TITLE
Sending text data to grammarly online

### ISSUE THREAD

**Issue by JKRT** [mmagnus/emacs-grammarly#9]
Currently, it works locally by passing text to a desktop client. I would however much like to communicate with the Grammarly webpage. I put this text up here as an enhancement issue

**Comment by JKRT** [comment]
If possible I could see if I could help : ) Do you know any place where I can start?

**Comment by mmagnus** [comment]
Yeah, that's an interesting idea, but I'm super short on time and I'm not able to work on that. 

What this plugin does, it saves a file to your computer, so technically, if then you can send this file to Grammarly online you can get this done...

**Comment by JKRT** [comment]
Hi!

If I would be able to pull something off, would you accept such a change?

**Comment by mmagnus** [comment]
@JKRT yeah, sure!
